---
- hosts: all
  become: true
  user: vagrant

  #we will gather facts later after ensuring python is installed
  gather_facts: False

  #Ubuntu 16.04 doesnt come with python 2.7 which ansible uses. 
  #so we will use a raw command to install it before we gather_facts
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: #get the gather_facts

  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: Install php
      apt: name={{item}} state=present
      with_items:
        - php7.0
        - nginx
        - php7.0-fpm
        - php7.0-mbstring
        - php7.0-mysql
        - php7.0-zip
        - redis-server
        - golang-go

    #Clone PHP Application Repo
    - name: Clone PHP Repo
      git:
        repo: git@github.com:gitBC/kochava-php.git
        dest: /var/www
        update: yes
        accept_hostkey: yes

    ##Set NGINX Config
    - name: Copy template Nginx Site config into place
      template: 
        src=templates/nginx.conf.j2
        dest=/etc/nginx/sites-available/koc.app
    - name: enable the site in nginx
      file:
        src=/etc/nginx/sites-available/koc.app
        dest=/etc/nginx/sites-enabled/koc.app
        state=link
    - name: restart nginx to ensure site conf found
      service: name=nginx state=restarted

    ##Set REDIS Config
    - name: Copy template REDIS Site config into place
      template: 
        src=templates/redis.conf.j2
        dest=/etc/redis/redis.conf
    - name: restart Redis to ensure new conf found
      service: name=nginx state=restarted

