
######### PHP VARS #########

php_app_env: "{{vault_php_app_env}}"
php_app_debug: "{{vault_php_app_debug}}"
php_app_key: "{{vault_php_app_key}}"
php_app_timezone: "{{vault_php_app_timezone}}"

php_db_connection: "{{vault_php_db_connection}}"
php_db_host: "{{vault_php_db_host}}"
php_db_port: "{{vault_php_db_port}}"
php_db_database: "{{vault_php_db_database}}"
php_db_username: "{{vault_php_db_username}}"
php_db_password: "{{vault_php_db_password}}"

php_cache_driver: "{{vault_php_cache_driver}}"
php_queue_driver: "{{vault_php_queue_driver}}"

php_redis_cluster: "{{vault_php_redis_cluster}}"
php_redis_host: "{{vault_php_redis_host}}"
php_redis_port: "{{vault_php_redis_port}}"
php_redis_database: "{{vault_php_redis_database}}"
php_redis_password: "{{vault_php_redis_password}}"


######### GO VARS #########

go_redis_server: "{{vault_go_redis_server}}"
go_redis_port: "{{vault_go_redis_port}}"
go_redis_password: "{{vault_go_redis_password}}"
go_redis_database: "{{vault_go_redis_database}}"

go_redis_delivery_attempts: "{{vault_go_redis_delivery_attempts}}"

go_details_api: "{{vault_go_details_api}}"